services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./quiz_engine:/app/quiz_engine
      # Mount your local Firebase JSON (read-only)
      - ./backend/db/serviceAccountKey.json:/app/backend/db/serviceAccountKey.json:ro
    environment:
      - ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/backend/db/serviceAccountKey.json

  frontend:
    image: node:18
    container_name: nexus_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npx serve -s . -l 3000"
